[theme]
primaryColor = "#00305F"    # Granat PKO
backgroundColor = "#FFFFFF" # Białe tło
secondaryBackgroundColor = "#F0F2F6" # Jasnoszare tło menu
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true